version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
      target: develop
    environment:
      - DATABASE_URL=pgsql://laravel:secret@db:5432/laravel?charset=utf8&prefix_indexes=true&schema=public&sslmode=prefer
      - LANG=C.UTF-8
      - TZ=Asia/Tokyo
    ports:
      - "80:80"
  db:
    image: postgres:13.2
    environment:
      - LANG=C.UTF-8
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=laravel
      - POSTGRES_DB=laravel
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C.UTF-8
      - TZ=Asia/Tokyo
